/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* LED_Pin */
#define LED_Pin_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Pin_0_INBUF_ENABLED 0u
#define LED_Pin_0_INIT_DRIVESTATE 0u
#define LED_Pin_0_INIT_MUXSEL 0u
#define LED_Pin_0_INPUT_SYNC 2u
#define LED_Pin_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Pin_0_NUM 1u
#define LED_Pin_0_PORT GPIO_PRT7
#define LED_Pin_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Pin_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_Pin_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Pin_INBUF_ENABLED 0u
#define LED_Pin_INIT_DRIVESTATE 0u
#define LED_Pin_INIT_MUXSEL 0u
#define LED_Pin_INPUT_SYNC 2u
#define LED_Pin_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Pin_NUM 1u
#define LED_Pin_PORT GPIO_PRT7
#define LED_Pin_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Pin_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_1_Sns */
#define CapSense_1_Sns_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_1_Sns_0_INBUF_ENABLED 0u
#define CapSense_1_Sns_0_INIT_DRIVESTATE 1u
#define CapSense_1_Sns_0_INIT_MUXSEL 0u
#define CapSense_1_Sns_0_INPUT_SYNC 2u
#define CapSense_1_Sns_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_1_Sns_0_NUM 2u
#define CapSense_1_Sns_0_PORT GPIO_PRT6
#define CapSense_1_Sns_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_1_Sns_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_1_Sns_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_1_Sns_INBUF_ENABLED 0u
#define CapSense_1_Sns_INIT_DRIVESTATE 1u
#define CapSense_1_Sns_INIT_MUXSEL 0u
#define CapSense_1_Sns_INPUT_SYNC 2u
#define CapSense_1_Sns_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_1_Sns_NUM 2u
#define CapSense_1_Sns_PORT GPIO_PRT6
#define CapSense_1_Sns_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_1_Sns_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_1_Cmod */
#define CapSense_1_Cmod_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_1_Cmod_0_INBUF_ENABLED 0u
#define CapSense_1_Cmod_0_INIT_DRIVESTATE 1u
#define CapSense_1_Cmod_0_INIT_MUXSEL 0u
#define CapSense_1_Cmod_0_INPUT_SYNC 2u
#define CapSense_1_Cmod_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_1_Cmod_0_NUM 7u
#define CapSense_1_Cmod_0_PORT GPIO_PRT7
#define CapSense_1_Cmod_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_1_Cmod_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_1_Cmod_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_1_Cmod_INBUF_ENABLED 0u
#define CapSense_1_Cmod_INIT_DRIVESTATE 1u
#define CapSense_1_Cmod_INIT_MUXSEL 0u
#define CapSense_1_Cmod_INPUT_SYNC 2u
#define CapSense_1_Cmod_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_1_Cmod_NUM 7u
#define CapSense_1_Cmod_PORT GPIO_PRT7
#define CapSense_1_Cmod_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_1_Cmod_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
