/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* LED */
#define LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_0_INBUF_ENABLED 0u
#define LED_0_INIT_DRIVESTATE 0u
#define LED_0_INIT_MUXSEL 0u
#define LED_0_INPUT_SYNC 2u
#define LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_0_NUM 6u
#define LED_0_PORT GPIO_PRT9
#define LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_INBUF_ENABLED 0u
#define LED_INIT_DRIVESTATE 0u
#define LED_INIT_MUXSEL 0u
#define LED_INPUT_SYNC 2u
#define LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_NUM 6u
#define LED_PORT GPIO_PRT9
#define LED_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_rx */
#define UART_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_0_INBUF_ENABLED 1u
#define UART_rx_0_INIT_DRIVESTATE 1u
#define UART_rx_0_INIT_MUXSEL 18u
#define UART_rx_0_INPUT_SYNC 2u
#define UART_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_0_NUM 0u
#define UART_rx_0_PORT GPIO_PRT10
#define UART_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_INBUF_ENABLED 1u
#define UART_rx_INIT_DRIVESTATE 1u
#define UART_rx_INIT_MUXSEL 18u
#define UART_rx_INPUT_SYNC 2u
#define UART_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_NUM 0u
#define UART_rx_PORT GPIO_PRT10
#define UART_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_tx */
#define UART_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_0_INBUF_ENABLED 0u
#define UART_tx_0_INIT_DRIVESTATE 1u
#define UART_tx_0_INIT_MUXSEL 18u
#define UART_tx_0_INPUT_SYNC 2u
#define UART_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_0_NUM 1u
#define UART_tx_0_PORT GPIO_PRT10
#define UART_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_INBUF_ENABLED 0u
#define UART_tx_INIT_DRIVESTATE 1u
#define UART_tx_INIT_MUXSEL 18u
#define UART_tx_INPUT_SYNC 2u
#define UART_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_NUM 1u
#define UART_tx_PORT GPIO_PRT10
#define UART_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* ButtonDrive */
#define ButtonDrive_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define ButtonDrive_0_INBUF_ENABLED 1u
#define ButtonDrive_0_INIT_DRIVESTATE 0u
#define ButtonDrive_0_INIT_MUXSEL 0u
#define ButtonDrive_0_INPUT_SYNC 2u
#define ButtonDrive_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define ButtonDrive_0_NUM 3u
#define ButtonDrive_0_PORT GPIO_PRT10
#define ButtonDrive_0_SLEWRATE CY_GPIO_SLEW_FAST
#define ButtonDrive_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define ButtonDrive_DRIVEMODE CY_GPIO_DM_HIGHZ
#define ButtonDrive_INBUF_ENABLED 1u
#define ButtonDrive_INIT_DRIVESTATE 0u
#define ButtonDrive_INIT_MUXSEL 0u
#define ButtonDrive_INPUT_SYNC 2u
#define ButtonDrive_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define ButtonDrive_NUM 3u
#define ButtonDrive_PORT GPIO_PRT10
#define ButtonDrive_SLEWRATE CY_GPIO_SLEW_FAST
#define ButtonDrive_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* ButtonSense */
#define ButtonSense_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define ButtonSense_0_INBUF_ENABLED 1u
#define ButtonSense_0_INIT_DRIVESTATE 0u
#define ButtonSense_0_INIT_MUXSEL 0u
#define ButtonSense_0_INPUT_SYNC 2u
#define ButtonSense_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define ButtonSense_0_NUM 4u
#define ButtonSense_0_PORT GPIO_PRT10
#define ButtonSense_0_SLEWRATE CY_GPIO_SLEW_FAST
#define ButtonSense_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define ButtonSense_DRIVEMODE CY_GPIO_DM_HIGHZ
#define ButtonSense_INBUF_ENABLED 1u
#define ButtonSense_INIT_DRIVESTATE 0u
#define ButtonSense_INIT_MUXSEL 0u
#define ButtonSense_INPUT_SYNC 2u
#define ButtonSense_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define ButtonSense_NUM 4u
#define ButtonSense_PORT GPIO_PRT10
#define ButtonSense_SLEWRATE CY_GPIO_SLEW_FAST
#define ButtonSense_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_Sns */
#define CapSense_Sns_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_0_INBUF_ENABLED 0u
#define CapSense_Sns_0_INIT_DRIVESTATE 1u
#define CapSense_Sns_0_INIT_MUXSEL 0u
#define CapSense_Sns_0_INPUT_SYNC 2u
#define CapSense_Sns_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_0_NUM 5u
#define CapSense_Sns_0_PORT GPIO_PRT10
#define CapSense_Sns_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_INBUF_ENABLED 0u
#define CapSense_Sns_INIT_DRIVESTATE 1u
#define CapSense_Sns_INIT_MUXSEL 0u
#define CapSense_Sns_INPUT_SYNC 2u
#define CapSense_Sns_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_NUM 5u
#define CapSense_Sns_PORT GPIO_PRT10
#define CapSense_Sns_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_Cmod */
#define CapSense_Cmod_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Cmod_0_INBUF_ENABLED 0u
#define CapSense_Cmod_0_INIT_DRIVESTATE 1u
#define CapSense_Cmod_0_INIT_MUXSEL 0u
#define CapSense_Cmod_0_INPUT_SYNC 2u
#define CapSense_Cmod_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Cmod_0_NUM 1u
#define CapSense_Cmod_0_PORT GPIO_PRT7
#define CapSense_Cmod_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Cmod_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Cmod_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Cmod_INBUF_ENABLED 0u
#define CapSense_Cmod_INIT_DRIVESTATE 1u
#define CapSense_Cmod_INIT_MUXSEL 0u
#define CapSense_Cmod_INPUT_SYNC 2u
#define CapSense_Cmod_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Cmod_NUM 1u
#define CapSense_Cmod_PORT GPIO_PRT7
#define CapSense_Cmod_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Cmod_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
